orbs:
  docker: circleci/docker@1.5.0
version: 2.1

executors:
  docker-publisher: 
    environment:
      IMAGE_NAME: abdalodj/udacity-simple-node-exo
    docker: # Each job requires specifying an executor
    # (either docker, macos, or machine), see
      - image: circleci/node:13.14.0
        auth:
            username: $DOCKER_USERNAME
            password: $DOCKER_PASSWORD

# Define the jobs we want to run for this project
jobs:
  publishLatestToHub:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: Publish Docker Image to Docker Hub
          command: |
            docker --version # print the version for logging
            docker build -t udacity-simple-node-exo .
            docker tag udacity-simple-node-exo abdalodj/udacity-simple-node-exo:latest

  test:
    docker:
      - image: cimg/node:13.14.0
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "docker push abdalodj/udacity-simple-node-exo"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build

# language: node_js
# node_js:
#   - 13

# services:
#   - docker

# # Pre-testing installs
# install:
#   - echo "nothing needs to be installed"

# # Scripts to be run such as tests
# before_script:
#   - echo "no tests"

# script:
#   - docker --version # print the version for logging
#   - docker build -t simple-node .
#   - docker tag simple-node YOUR_DOCKER_HUB/simple-node:latest

# after_success:
#   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#   - docker push YOUR_DOCKER_HUB/simple-node
